In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

2.2.2

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
df = pd.read_csv('/content/drive/MyDrive/DSRM/Lecture_2/dirty_data.csv')

In [5]:
df.head()

,Id,Timestamp,What is your gender?,What colour are your eyes?,"On average, how long does it take you to get from home to the University (in minutes)?",How tall are you (in cm)?
0,58,9/24/2018 15:31:57,Female,green,50,152
1,15,9/24/2018 22:44:36,Male,Black,40,175
2,34,9/25/2018 16:36:17,Male,Black,15,179
3,4,9/26/2018 1:25:27,Male,brown,27,180
4,69,9/26/2018 12:46:21,Male,Blue,NaN,175

In [6]:
df.columns

Index(['Id', 'Timestamp', 'What is your gender?', 'What colour are your eyes?',
       'On average, how long does it take you to get from home to the University (in minutes)?',
       'How tall are you (in cm)?'],
      dtype='object')

In [7]:
df.head(10)

,Id,Timestamp,What is your gender?,What colour are your eyes?,"On average, how long does it take you to get from home to the University (in minutes)?",How tall are you (in cm)?
0,58,9/24/2018 15:31:57,Female,green,50,152
1,15,9/24/2018 22:44:36,Male,Black,40,175
2,34,9/25/2018 16:36:17,Male,Black,15,179
3,4,9/26/2018 1:25:27,Male,brown,27,180
4,69,9/26/2018 12:46:21,Male,Blue,NaN,175
5,0,9/26/2018 17:37:58,Male,BLACK,apx. 120,174
6,53,9/27/2018 11:49:08,Female,Green,25,160
7,73,10/01/2018 18:51,Female,Brown,10,157
8,49,10/03/2018 17:22,Male,Brown,20min,179.83cm
9,0,10/03/2018 23:50,Female,Black,10,NaN

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 6 columns):
 #   Column                                                                                  Non-Null Count  Dtype
---  ------                                                                                  --------------  -----
 0   Id                                                                                      86 non-null     int64
 1   Timestamp                                                                               86 non-null     object
 2   What is your gender?                                                                    86 non-null     object
 3   What colour are your eyes?                                                              86 non-null     object
 4   On average, how long does it take you to get from home to the University (in minutes)?  82 non-null     object
 5   How tall are you (in cm)?                                                               85 non-null     object
dtypes: int64(1), object(5)
memory usage: 4.2+ KB

In [9]:
df.describe()

              Id
count  86.000000
mean   32.604651
std    20.245132
min     0.000000
25%    19.000000
50%    32.000000
75%    47.000000
max    74.000000

In [10]:
df.describe(include='all')

,Id,Timestamp,What is your gender?,What colour are your eyes?,"On average, how long does it take you to get from home to the University (in minutes)?",How tall are you (in cm)?
count,86.000000,86,86,86,82,85
unique,NaN,83,4,17,31,41
top,NaN,10/03/2018 23:51,Male,Brown,30,175
freq,NaN,3,52,21,10,8
mean,32.604651,NaN,NaN,NaN,NaN,NaN
std,20.245132,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,NaN,NaN
25%,19.000000,NaN,NaN,NaN,NaN,NaN
50%,32.000000,NaN,NaN,NaN,NaN,NaN
75%,47.000000,NaN,NaN,NaN,NaN,NaN
max,74.000000,NaN,NaN,NaN,NaN,NaN

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 6 columns):
 #   Column                                                                                  Non-Null Count  Dtype
---  ------                                                                                  --------------  -----
 0   Id                                                                                      86 non-null     int64
 1   Timestamp                                                                               86 non-null     object
 2   What is your gender?                                                                    86 non-null     object
 3   What colour are your eyes?                                                              86 non-null     object
 4   On average, how long does it take you to get from home to the University (in minutes)?  82 non-null     object
 5   How tall are you (in cm)?                                                               85 non-null     object
dtypes: int64(1), object(5)
memory usage: 4.2+ KB

**RENAME COLUMN**

In [13]:
columns = {'What is your gender?':'Gender', 'What colour are your eyes?': 'eye color'}

In [14]:
df.rename(columns=columns, inplace=True)

In [15]:
df.columns

Index(['Id', 'Timestamp', 'Gender', 'eye color',
       'On average, how long does it take you to get from home to the University (in minutes)?',
       'How tall are you (in cm)?'],
      dtype='object')

In [16]:
columns = {'On average, how long does it take you to get from home to the University (in minutes)?':'commute_time'}

In [17]:
df.rename(columns=columns, inplace=True)

In [18]:
df.columns

Index(['Id', 'Timestamp', 'Gender', 'eye color', 'commute_time',
       'How tall are you (in cm)?'],
      dtype='object')

In [19]:
columns = {'How tall are you (in cm)?':'height'}

In [20]:
df.rename(columns=columns, inplace=True)

In [21]:
df.columns

Index(['Id', 'Timestamp', 'Gender', 'eye color', 'commute_time', 'height'], dtype='object')

In [22]:
df.head()

   Id           Timestamp  Gender eye color commute_time height
0  58  9/24/2018 15:31:57  Female     green           50    152
1  15  9/24/2018 22:44:36    Male     Black           40    175
2  34  9/25/2018 16:36:17    Male     Black           15    179
3   4   9/26/2018 1:25:27    Male     brown           27    180
4  69  9/26/2018 12:46:21    Male      Blue          NaN    175

In [23]:
df.describe()

              Id
count  86.000000
mean   32.604651
std    20.245132
min     0.000000
25%    19.000000
50%    32.000000
75%    47.000000
max    74.000000

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            86 non-null     int64
 1   Timestamp     86 non-null     object
 2   Gender        86 non-null     object
 3   eye color     86 non-null     object
 4   commute_time  82 non-null     object
 5   height        85 non-null     object
dtypes: int64(1), object(5)
memory usage: 4.2+ KB

In [25]:
columns = {'Id':'id', 'Timestamp':'timestamp', 'Gender':'gender'}

In [26]:
df.rename(columns=columns, inplace = True)

In [27]:
df.columns

Index(['id', 'timestamp', 'gender', 'eye color', 'commute_time', 'height'], dtype='object')

In [28]:
df[df['id'].isnull()]

Empty DataFrame
Columns: [id, timestamp, gender, eye color, commute_time, height]
Index: []

In [29]:
df[df['timestamp'].isnull()]

Empty DataFrame
Columns: [id, timestamp, gender, eye color, commute_time, height]
Index: []

In [30]:
df[df['height'].isnull()]

   id         timestamp  gender eye color commute_time height
9   0  10/03/2018 23:50  Female     Black           10    NaN

In [31]:
df[df['height'].isnull()|df['commute_time'].isnull()]

    id           timestamp  gender eye color commute_time height
4   69  9/26/2018 12:46:21    Male      Blue          NaN    175
9    0    10/03/2018 23:50  Female     Black           10    NaN
31  25    10/07/2018 22:32    Male     black          NaN    177
79  19    10/01/2020 01:45    Male    Black           NaN    163
80  22    10/01/2020 01:45    Male    Black           NaN    163

In [32]:
df.columns

Index(['id', 'timestamp', 'gender', 'eye color', 'commute_time', 'height'], dtype='object')

In [33]:
df[df['gender'].isnull()]

Empty DataFrame
Columns: [id, timestamp, gender, eye color, commute_time, height]
Index: []

In [34]:
df[df['timestamp'].isnull()]

Empty DataFrame
Columns: [id, timestamp, gender, eye color, commute_time, height]
Index: []

In [35]:
df[df['gender'].isnull()]

Empty DataFrame
Columns: [id, timestamp, gender, eye color, commute_time, height]
Index: []

In [36]:
df[df['eye color'].isnull()]

Empty DataFrame
Columns: [id, timestamp, gender, eye color, commute_time, height]
Index: []

In [37]:
df[df['id'].isnull()|df['timestamp'].isnull()|df['height'].isnull()|df['gender'].isnull()|df['eye color'].isnull()|df['commute_time'].isnull()]

    id           timestamp  gender eye color commute_time height
4   69  9/26/2018 12:46:21    Male      Blue          NaN    175
9    0    10/03/2018 23:50  Female     Black           10    NaN
31  25    10/07/2018 22:32    Male     black          NaN    177
79  19    10/01/2020 01:45    Male    Black           NaN    163
80  22    10/01/2020 01:45    Male    Black           NaN    163

In [38]:
nan_indexes = df[df['id'].isnull()|df['timestamp'].isnull()|df['height'].isnull()|df['gender'].isnull()|df['eye color'].isnull()|df['commute_time'].isnull()].index

In [39]:
df.loc[nan_indexes]

    id           timestamp  gender eye color commute_time height
4   69  9/26/2018 12:46:21    Male      Blue          NaN    175
9    0    10/03/2018 23:50  Female     Black           10    NaN
31  25    10/07/2018 22:32    Male     black          NaN    177
79  19    10/01/2020 01:45    Male    Black           NaN    163
80  22    10/01/2020 01:45    Male    Black           NaN    163

In [40]:
df=df.drop(nan_indexes)

In [41]:
df.columns

Index(['id', 'timestamp', 'gender', 'eye color', 'commute_time', 'height'], dtype='object')

**drop null**

In [42]:
df.reset_index(drop=True, inplace=True)

In [43]:
print(df.duplicated('id').any())

True

remove duplicates

In [44]:
sum(df.duplicated('id'))

30

In [45]:
pd.unique(df[df.duplicated('id')]['id'])

array([19, 53, 15, 66, 12, 39,  8,  9, 40, 35, 45, 47, 22, 20,  7,  0, 25,
       31,  5])

In [46]:
df[df['id']==19]

    id           timestamp  gender eye color commute_time height
16  19    10/04/2018 09:07  Female      Blue           35    158
19  19    10/04/2018 10:32  Female     Brown           60    160
27  19    10/05/2018 13:50    Male     Black           20    169
62  19  9/30/2020 15:07:20    Male     Brown           50    176

In [47]:
df.drop_duplicates(subset = ['id'], keep='last', inplace = True, ignore_index = True )

In [48]:
df[df['id']==19]

    id           timestamp gender eye color commute_time height
34  19  9/30/2020 15:07:20   Male     Brown           50    176

In [49]:
df.reset_index(drop=True, inplace=True)

In [50]:
df.duplicated('id').any()

np.False_

In [51]:
print(df.duplicated('id').any())

False

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            51 non-null     int64
 1   timestamp     51 non-null     object
 2   gender        51 non-null     object
 3   eye color     51 non-null     object
 4   commute_time  51 non-null     object
 5   height        51 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.5+ KB

In [53]:
df['commute_time']

0                                   50
1                                   15
2                                   27
3                                   10
4                                20min
5                               1 hour
6                               40mins
7                                   35
8                                   30
9                                   10
10                                  15
11                                  40
12                                  20
13                                  30
14                                  15
15                                  32
16                             2.5 hrs
17                                  30
18                                  20
19                                  50
20                                  15
21                                  20
22                             40 mins
23                                  30
24                                  50
25                                   5
26                                  60
27                                  30
28                                  30
29                                 120
30                                  35
31                                  40
32                                   0
33                                  35
34                                  50
35                                  35
36                                  45
37            3 when I live on campus
38                                  60
39                          30 minutes
40                          20 minutes
41                                  30
42                                  15
43                                  20
44                                  30
45    I live on campus accommodation.
46                                  45
47                                  15
48                                  90
49                                  10
50                            apx. 120
Name: commute_time, dtype: object

In [54]:
df.commute_time

0                                   50
1                                   15
2                                   27
3                                   10
4                                20min
5                               1 hour
6                               40mins
7                                   35
8                                   30
9                                   10
10                                  15
11                                  40
12                                  20
13                                  30
14                                  15
15                                  32
16                             2.5 hrs
17                                  30
18                                  20
19                                  50
20                                  15
21                                  20
22                             40 mins
23                                  30
24                                  50
25                                   5
26                                  60
27                                  30
28                                  30
29                                 120
30                                  35
31                                  40
32                                   0
33                                  35
34                                  50
35                                  35
36                                  45
37            3 when I live on campus
38                                  60
39                          30 minutes
40                          20 minutes
41                                  30
42                                  15
43                                  20
44                                  30
45    I live on campus accommodation.
46                                  45
47                                  15
48                                  90
49                                  10
50                            apx. 120
Name: commute_time, dtype: object

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            51 non-null     int64
 1   timestamp     51 non-null     object
 2   gender        51 non-null     object
 3   eye color     51 non-null     object
 4   commute_time  51 non-null     object
 5   height        51 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.5+ KB

In [56]:
df['timestamp'][0]

'9/24/2018 15:31:57'

In [57]:
df.timestamp[0]

'9/24/2018 15:31:57'

In [58]:
type(df['timestamp'][0])

str

In [59]:
type(df['height'][3])

str

In [60]:
df.timestamp

0     9/24/2018 15:31:57
1     9/25/2018 16:36:17
2      9/26/2018 1:25:27
3       10/01/2018 18:51
4       10/03/2018 17:22
5       10/03/2018 23:51
6       10/03/2018 23:55
7       10/04/2018 06:34
8       10/04/2018 09:19
9       10/04/2018 10:03
10      10/04/2018 11:00
11      10/04/2018 12:06
12      10/04/2018 13:43
13      10/04/2018 14:08
14      10/04/2018 16:02
15      10/06/2018 16:01
16      10/09/2018 01:37
17    9/30/2019 14:31:41
18    9/30/2019 14:31:48
19      10/01/2019 11:09
20      10/01/2019 13:25
21    10/16/2019 9:20:48
22    9/28/2020 22:39:35
23    9/29/2020 15:11:45
24    9/29/2020 17:57:05
25    9/30/2020 11:34:10
26    9/30/2020 12:08:29
27    9/30/2020 12:22:36
28    9/30/2020 12:55:57
29    9/30/2020 13:57:48
30    9/30/2020 14:02:20
31    9/30/2020 14:07:08
32    9/30/2020 14:10:13
33    9/30/2020 15:07:19
34    9/30/2020 15:07:20
35    9/30/2020 15:11:03
36    9/30/2020 15:12:58
37    9/30/2020 15:17:53
38    9/30/2020 15:32:21
39    9/30/2020 15:35:26
40    9/30/2020 15:41:22
41    9/30/2020 15:51:18
42    9/30/2020 15:53:45
43    9/30/2020 16:39:07
44    9/30/2020 16:51:49
45    9/30/2020 17:03:36
46    9/30/2020 17:35:05
47      10/01/2020 12:39
48      10/02/2020 09:18
49      10/07/2020 10:08
50      10/08/2020 11:48
Name: timestamp, dtype: object

In [61]:
df.timestamp = pd.to_datetime(df.timestamp, format='mixed')

In [62]:
df.timestamp[0]

Timestamp('2018-09-24 15:31:57')

**This next topic is about feature engineering / wrangling — creating new columns from existing data.**

Since i just converted timestamps into proper datetime values, now pandas can
extract useful pieces from them.

can create new columns like:

df["year"] = df.timestamp.dt.year
df["month"] = df.timestamp.dt.month
df["day"] = df.timestamp.dt.day
df["hour"] = df.timestamp.dt.hour

In [63]:
df.timestamp

0    2018-09-24 15:31:57
1    2018-09-25 16:36:17
2    2018-09-26 01:25:27
3    2018-10-01 18:51:00
4    2018-10-03 17:22:00
5    2018-10-03 23:51:00
6    2018-10-03 23:55:00
7    2018-10-04 06:34:00
8    2018-10-04 09:19:00
9    2018-10-04 10:03:00
10   2018-10-04 11:00:00
11   2018-10-04 12:06:00
12   2018-10-04 13:43:00
13   2018-10-04 14:08:00
14   2018-10-04 16:02:00
15   2018-10-06 16:01:00
16   2018-10-09 01:37:00
17   2019-09-30 14:31:41
18   2019-09-30 14:31:48
19   2019-10-01 11:09:00
20   2019-10-01 13:25:00
21   2019-10-16 09:20:48
22   2020-09-28 22:39:35
23   2020-09-29 15:11:45
24   2020-09-29 17:57:05
25   2020-09-30 11:34:10
26   2020-09-30 12:08:29
27   2020-09-30 12:22:36
28   2020-09-30 12:55:57
29   2020-09-30 13:57:48
30   2020-09-30 14:02:20
31   2020-09-30 14:07:08
32   2020-09-30 14:10:13
33   2020-09-30 15:07:19
34   2020-09-30 15:07:20
35   2020-09-30 15:11:03
36   2020-09-30 15:12:58
37   2020-09-30 15:17:53
38   2020-09-30 15:32:21
39   2020-09-30 15:35:26
40   2020-09-30 15:41:22
41   2020-09-30 15:51:18
42   2020-09-30 15:53:45
43   2020-09-30 16:39:07
44   2020-09-30 16:51:49
45   2020-09-30 17:03:36
46   2020-09-30 17:35:05
47   2020-10-01 12:39:00
48   2020-10-02 09:18:00
49   2020-10-07 10:08:00
50   2020-10-08 11:48:00
Name: timestamp, dtype: datetime64[ns]

**ALL timestamps follow ONE consistent pattern**

In [64]:
timestamp_format = '%m/%d/%y %H:%M:%S'
df.timestamp = pd.to_datetime(df.timestamp, format='timestamp_format')

In [65]:
df.timestamp[50]

Timestamp('2020-10-08 11:48:00')

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            51 non-null     int64
 1   timestamp     51 non-null     datetime64[ns]
 2   gender        51 non-null     object
 3   eye color     51 non-null     object
 4   commute_time  51 non-null     object
 5   height        51 non-null     object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 2.5+ KB

In [67]:
df['date'] = df.timestamp.dt.date

In [68]:
df.head()

   id           timestamp  gender eye color commute_time    height        date
0  58 2018-09-24 15:31:57  Female     green           50       152  2018-09-24
1  34 2018-09-25 16:36:17    Male     Black           15       179  2018-09-25
2   4 2018-09-26 01:25:27    Male     brown           27       180  2018-09-26
3  73 2018-10-01 18:51:00  Female     Brown           10       157  2018-10-01
4  49 2018-10-03 17:22:00    Male     Brown        20min  179.83cm  2018-10-03

In [69]:
df['time'] = df.timestamp.dt.time

In [70]:
df.head()

,id,timestamp,gender,eye color,commute_time,height,date,time
0,58,2018-09-24 15:31:57,Female,green,50,152,2018-09-24,15:31:57
1,34,2018-09-25 16:36:17,Male,Black,15,179,2018-09-25,16:36:17
2,4,2018-09-26 01:25:27,Male,brown,27,180,2018-09-26,01:25:27
3,73,2018-10-01 18:51:00,Female,Brown,10,157,2018-10-01,18:51:00
4,49,2018-10-03 17:22:00,Male,Brown,20min,179.83cm,2018-10-03,17:22:00

In [71]:
df['year'] = df.timestamp.dt.year

In [72]:
df.head()

,id,timestamp,gender,eye color,commute_time,height,date,time,year
0,58,2018-09-24 15:31:57,Female,green,50,152,2018-09-24,15:31:57,2018
1,34,2018-09-25 16:36:17,Male,Black,15,179,2018-09-25,16:36:17,2018
2,4,2018-09-26 01:25:27,Male,brown,27,180,2018-09-26,01:25:27,2018
3,73,2018-10-01 18:51:00,Female,Brown,10,157,2018-10-01,18:51:00,2018
4,49,2018-10-03 17:22:00,Male,Brown,20min,179.83cm,2018-10-03,17:22:00,2018

In [73]:
df.timestamp.dt.year.unique()

array([2018, 2019, 2020], dtype=int32)

In [74]:
df.timestamp.dt.year.nunique()

3

In [75]:
df.head(30)

,id,timestamp,gender,eye color,commute_time,height,date,time,year
0,58,2018-09-24 15:31:57,Female,green,50,152,2018-09-24,15:31:57,2018
1,34,2018-09-25 16:36:17,Male,Black,15,179,2018-09-25,16:36:17,2018
2,4,2018-09-26 01:25:27,Male,brown,27,180,2018-09-26,01:25:27,2018
3,73,2018-10-01 18:51:00,Female,Brown,10,157,2018-10-01,18:51:00,2018
4,49,2018-10-03 17:22:00,Male,Brown,20min,179.83cm,2018-10-03,17:22:00,2018
5,43,2018-10-03 23:51:00,Prefer not to say,borwn,1 hour,"6'4""",2018-10-03,23:51:00,2018
6,56,2018-10-03 23:55:00,Non binary,Blueish,40mins,175,2018-10-03,23:55:00,2018
7,48,2018-10-04 06:34:00,Male,Green,35,"1,82",2018-10-04,06:34:00,2018
8,28,2018-10-04 09:19:00,Male,Green,30,180.34,2018-10-04,09:19:00,2018
9,57,2018-10-04 10:03:00,Male,brown,10,173,2018-10-04,10:03:00,2018
10,67,2018-10-04 11:00:00,Male,Blue,15,178,2018-10-04,11:00:00,2018
11,15,2018-10-04 12:06:00,Female,Brown,40,158,2018-10-04,12:06:00,2018
12,65,2018-10-04 13:43:00,Male,black,20,177,2018-10-04,13:43:00,2018
13,66,2018-10-04 14:08:00,Female,green,30,170,2018-10-04,14:08:00,2018
14,12,2018-10-04 16:02:00,Male,brown,15,188,2018-10-04,16:02:00,2018
15,61,2018-10-06 16:01:00,Male,blue,32,175,2018-10-06,16:01:00,2018
16,3,2018-10-09 01:37:00,Male,brown,2.5 hrs,183,2018-10-09,01:37:00,2018
17,50,2019-09-30 14:31:41,Male,Brown,30,186,2019-09-30,14:31:41,2019
18,69,2019-09-30 14:31:48,Male,brown,20,175,2019-09-30,14:31:48,2019
19,14,2019-10-01 11:09:00,Female,brown,50,173,2019-10-01,11:09:00,2019
20,38,2019-10-01 13:25:00,Male,Hazel,15,175,2019-10-01,13:25:00,2019
21,8,2019-10-16 09:20:48,Female,brown,20,160,2019-10-16,09:20:48,2019
22,9,2020-09-28 22:39:35,Female,Brown,40 mins,157,2020-09-28,22:39:35,2020
23,40,2020-09-29 15:11:45,Male,brown,30,200,2020-09-29,15:11:45,2020
24,74,2020-09-29 17:57:05,Male,brown,50,175,2020-09-29,17:57:05,2020
25,21,2020-09-30 11:34:10,Male,Hazel,5,183,2020-09-30,11:34:10,2020
26,47,2020-09-30 12:08:29,Male,Hazel,60,162,2020-09-30,12:08:29,2020
27,26,2020-09-30 12:22:36,Male,brown,30,183,2020-09-30,12:22:36,2020
28,53,2020-09-30 12:55:57,Male,blue,30,189,2020-09-30,12:55:57,2020
29,36,2020-09-30 13:57:48,Female,black,120,162,2020-09-30,13:57:48,2020

In [76]:
df.timestamp.dt.year.value_counts()

timestamp
2020    29
2018    17
2019     5
Name: count, dtype: int64

In [77]:
df['commute_time'].unique()

array(['50', '15', '27', '10', '20min', '1 hour', '40mins', '35', '30',
       '40', '20', '32', '2.5 hrs', '40 mins', '5', '60', '120', '0',
       '45', '3 when I live on campus ', '30 minutes', '20 minutes',
       'I live on campus accommodation. ', '90', 'apx. 120'], dtype=object)

In [78]:
df['eye color'].unique()

array(['green', 'Black', 'brown', 'Brown', 'borwn', 'Blueish', 'Green ',
       'Green', 'Blue', 'black', 'blue', 'Hazel', 'Dark brown ',
       'Dark brown'], dtype=object)

In [79]:
df['eye color'].value_counts()

eye color
Brown          13
brown          13
Green           5
Hazel           4
blue            3
Black           2
black           2
Blue            2
green           2
borwn           1
Blueish         1
Green           1
Dark brown      1
Dark brown      1
Name: count, dtype: int64

In [80]:
unique_gender = pd.unique(df.gender)

In [81]:
print(unique_gender)

['Female' 'Male' 'Prefer not to say' 'Non binary']

In [82]:
unique_gender_type = pd.unique([isinstance(x,str) for x in df.gender])

/tmp/ipykernel_78316/1503092502.py:1: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  unique_gender_type = pd.unique([isinstance(x,str) for x in df.gender])

In [83]:
print(unique_gender_type)

[ True]

In [84]:
unique_commute_type = pd.unique([isinstance(x,str) for x in df.commute_time])

/tmp/ipykernel_78316/2210995136.py:1: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  unique_commute_type = pd.unique([isinstance(x,str) for x in df.commute_time])

In [85]:
unique_commute = pd.unique(df.commute_time)

In [86]:
print(unique_commute)

['50' '15' '27' '10' '20min' '1 hour' '40mins' '35' '30' '40' '20' '32'
 '2.5 hrs' '40 mins' '5' '60' '120' '0' '45' '3 when I live on campus '
 '30 minutes' '20 minutes' 'I live on campus accommodation. ' '90'
 'apx. 120']

In [87]:
print(unique_commute_type)

[ True]

In [88]:
type(df.commute_time.iloc[0])

str

iloc means:

integer location

It is used to access rows/columns by POSITION NUMBER.

Syntax:

df.iloc[row_index]

or

df.iloc[row_index, column_index]

So in our code:

df.commute_time.iloc[4]

means:

go to column commute_time
take the value at position/index 4
(the 5th row, because counting starts from 0)

From our dataframe:

index	commute_time
0	50
1	15
2	27
3	10
4	20min

So:

df.commute_time.iloc[4]

returns:

"20min"

Then:

type(df.commute_time.iloc[4])

checks its datatype.

we can also do:

df.iloc[4]

→ gives the ENTIRE 5th row.

Or:

df.iloc[4, 2]

→ row 4, column 2.

Very heavily used in:

data cleaning
ML preprocessing
debugging
feature engineering
inspecting specific rows.

In [89]:
type(df.commute_time.iloc[4])

str

In [90]:
df.height.apply(lambda x: isinstance(x, str))

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
18    True
19    True
20    True
21    True
22    True
23    True
24    True
25    True
26    True
27    True
28    True
29    True
30    True
31    True
32    True
33    True
34    True
35    True
36    True
37    True
38    True
39    True
40    True
41    True
42    True
43    True
44    True
45    True
46    True
47    True
48    True
49    True
50    True
Name: height, dtype: bool

In [91]:
pd.unique(df.height.apply(lambda x: isinstance(x, str)))

array([ True])

In [92]:
df.columns

Index(['id', 'timestamp', 'gender', 'eye color', 'commute_time', 'height',
       'date', 'time', 'year'],
      dtype='object')

In [93]:
columns = {'eye color': 'eye_color'}

In [94]:
df.rename(columns=columns, inplace=True)

In [95]:
df.columns

Index(['id', 'timestamp', 'gender', 'eye_color', 'commute_time', 'height',
       'date', 'time', 'year'],
      dtype='object')

In [96]:
pd.unique(df.eye_color)

array(['green', 'Black', 'brown', 'Brown', 'borwn', 'Blueish', 'Green ',
       'Green', 'Blue', 'black', 'blue', 'Hazel', 'Dark brown ',
       'Dark brown'], dtype=object)

In [97]:
print(len(df))

51

In [98]:
print(df.eye_color.value_counts())

eye_color
Brown          13
brown          13
Green           5
Hazel           4
blue            3
Black           2
black           2
Blue            2
green           2
borwn           1
Blueish         1
Green           1
Dark brown      1
Dark brown      1
Name: count, dtype: int64

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            51 non-null     int64
 1   timestamp     51 non-null     datetime64[ns]
 2   gender        51 non-null     object
 3   eye_color     51 non-null     object
 4   commute_time  51 non-null     object
 5   height        51 non-null     object
 6   date          51 non-null     object
 7   time          51 non-null     object
 8   year          51 non-null     int32
dtypes: datetime64[ns](1), int32(1), int64(1), object(6)
memory usage: 3.5+ KB

In [100]:
pd.unique(df.eye_color)

array(['green', 'Black', 'brown', 'Brown', 'borwn', 'Blueish', 'Green ',
       'Green', 'Blue', 'black', 'blue', 'Hazel', 'Dark brown ',
       'Dark brown'], dtype=object)

**capitalization**

In [102]:
df.eye_color = df.eye_color.apply(lambda x : x.capitalize())

In [103]:
pd.unique(df.eye_color)

array(['Green', 'Black', 'Brown', 'Borwn', 'Blueish', 'Green ', 'Blue',
       'Hazel', 'Dark brown ', 'Dark brown'], dtype=object)

In [104]:
df.eye_color = df.eye_color.apply(lambda x: x.strip())

In [105]:
pd.unique(df.eye_color)

array(['Green', 'Black', 'Brown', 'Borwn', 'Blueish', 'Blue', 'Hazel',
       'Dark brown'], dtype=object)

In [106]:
# wrondf.loc[df.eye_color == 'Borwn'] == 'Brown'

In [107]:
pd.unique(df.eye_color)

array(['Green', 'Black', 'Brown', 'Borwn', 'Blueish', 'Blue', 'Hazel',
       'Dark brown'], dtype=object)

In [108]:
df.loc[df.eye_color == 'Borwn', 'eye_color'] = 'Brown'

In [109]:
pd.unique(df.eye_color)

array(['Green', 'Black', 'Brown', 'Blueish', 'Blue', 'Hazel',
       'Dark brown'], dtype=object)

In [110]:
df.eye_color.value_counts()

eye_color
Brown         27
Green          8
Blue           5
Black          4
Hazel          4
Dark brown     2
Blueish        1
Name: count, dtype: int64

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            51 non-null     int64
 1   timestamp     51 non-null     datetime64[ns]
 2   gender        51 non-null     object
 3   eye_color     51 non-null     object
 4   commute_time  51 non-null     object
 5   height        51 non-null     object
 6   date          51 non-null     object
 7   time          51 non-null     object
 8   year          51 non-null     int32
dtypes: datetime64[ns](1), int32(1), int64(1), object(6)
memory usage: 3.5+ KB

In [112]:
pd.unique(df.commute_time)

array(['50', '15', '27', '10', '20min', '1 hour', '40mins', '35', '30',
       '40', '20', '32', '2.5 hrs', '40 mins', '5', '60', '120', '0',
       '45', '3 when I live on campus ', '30 minutes', '20 minutes',
       'I live on campus accommodation. ', '90', 'apx. 120'], dtype=object)

In [113]:
columns = {'commute_time': 'commute_mins'}

In [114]:
df.rename(columns=columns, inplace=True)

In [115]:
df.head()

,id,timestamp,gender,eye_color,commute_mins,height,date,time,year
0,58,2018-09-24 15:31:57,Female,Green,50,152,2018-09-24,15:31:57,2018
1,34,2018-09-25 16:36:17,Male,Black,15,179,2018-09-25,16:36:17,2018
2,4,2018-09-26 01:25:27,Male,Brown,27,180,2018-09-26,01:25:27,2018
3,73,2018-10-01 18:51:00,Female,Brown,10,157,2018-10-01,18:51:00,2018
4,49,2018-10-03 17:22:00,Male,Brown,20min,179.83cm,2018-10-03,17:22:00,2018

In [116]:
pd.unique(df.commute_mins)

array(['50', '15', '27', '10', '20min', '1 hour', '40mins', '35', '30',
       '40', '20', '32', '2.5 hrs', '40 mins', '5', '60', '120', '0',
       '45', '3 when I live on campus ', '30 minutes', '20 minutes',
       'I live on campus accommodation. ', '90', 'apx. 120'], dtype=object)

In [117]:
df.head(5)

,id,timestamp,gender,eye_color,commute_mins,height,date,time,year
0,58,2018-09-24 15:31:57,Female,Green,50,152,2018-09-24,15:31:57,2018
1,34,2018-09-25 16:36:17,Male,Black,15,179,2018-09-25,16:36:17,2018
2,4,2018-09-26 01:25:27,Male,Brown,27,180,2018-09-26,01:25:27,2018
3,73,2018-10-01 18:51:00,Female,Brown,10,157,2018-10-01,18:51:00,2018
4,49,2018-10-03 17:22:00,Male,Brown,20min,179.83cm,2018-10-03,17:22:00,2018

In [118]:
pd.unique(df.commute_mins)

array(['50', '15', '27', '10', '20min', '1 hour', '40mins', '35', '30',
       '40', '20', '32', '2.5 hrs', '40 mins', '5', '60', '120', '0',
       '45', '3 when I live on campus ', '30 minutes', '20 minutes',
       'I live on campus accommodation. ', '90', 'apx. 120'], dtype=object)

In [119]:
def update_commute_times(val):
  splits = ['min','hr','hour']
  for substr in splits:
    if substr in val:
      split_idx = val.find(substr)
      new_val = float(val[:split_idx].strip())
      return new_val if substr == 'min' else 60.0*new_val

  substr = 'apx.'
  if substr in val:
    split_idx = val.find(substr)
    return float(val[split_idx + len(substr):].strip())

  if 'campus' in val:
    return 0

  return float(val)

tests = ['25', '20mins', '1hr', '2 hr', '3 hours', '4hours', '5-campus', '6 on-campus', 'apx.8','apx. 9']
print(tests)
print([update_commute_times(test) for test in tests])

['25', '20mins', '1hr', '2 hr', '3 hours', '4hours', '5-campus', '6 on-campus', 'apx.8', 'apx. 9']
[25.0, 20.0, 60.0, 120.0, 180.0, 240.0, 0, 0, 8.0, 9.0]

In [120]:
pd.unique(df.commute_mins)

array(['50', '15', '27', '10', '20min', '1 hour', '40mins', '35', '30',
       '40', '20', '32', '2.5 hrs', '40 mins', '5', '60', '120', '0',
       '45', '3 when I live on campus ', '30 minutes', '20 minutes',
       'I live on campus accommodation. ', '90', 'apx. 120'], dtype=object)

In [121]:
df.commute_mins = df.commute_mins.apply(update_commute_times)

In [122]:
pd.unique(df.commute_mins)

array([ 50.,  15.,  27.,  10.,  20.,  60.,  40.,  35.,  30.,  32., 150.,
         5., 120.,   0.,  45.,  90.])

In [123]:
pd.unique(df.height)

array(['152', '179', '180', '157', '179.83cm', '6\'4"', '175', '1,82',
       '180.34', '173', '178', '158', '177', '170', '188', '183', '186',
       '160', '200', '162', '189', '190cm', '190', '169', '176', '192',
       '182', '185', '155', '164', '166', '163', '165'], dtype=object)

In [124]:
df.columns

Index(['id', 'timestamp', 'gender', 'eye_color', 'commute_mins', 'height',
       'date', 'time', 'year'],
      dtype='object')

In [125]:
columns = {'height': 'height_cm'}

In [126]:
df.rename(columns=columns, inplace=True)

In [127]:
df.columns

Index(['id', 'timestamp', 'gender', 'eye_color', 'commute_mins', 'height_cm',
       'date', 'time', 'year'],
      dtype='object')

In [128]:
pd.unique(df.height_cm)

array(['152', '179', '180', '157', '179.83cm', '6\'4"', '175', '1,82',
       '180.34', '173', '178', '158', '177', '170', '188', '183', '186',
       '160', '200', '162', '189', '190cm', '190', '169', '176', '192',
       '182', '185', '155', '164', '166', '163', '165'], dtype=object)

In [129]:
def update_height(val):
  substr = 'cm'
  if substr in val:
    split_idx = val.find(substr)
    return float(val[:split_idx].strip())

  substr = '.'
  if substr in val:
    if val.find(substr) == 1:
      return float(val) * 100.0
    return float(val)

  substr = ','
  if substr in val:
    val = val.replace(substr,'.')
    return float(val) * 100.0

  substr = "\'"
  if substr in val:
    split_strs = val.replace("'"," ").replace('"','').split()
    feet = float(split_strs[0])
    inches = float(split_strs[1])

    return 2.54 * inches + 30.48*feet

  return float(val)

In [130]:
pd.unique(df.height_cm)

array(['152', '179', '180', '157', '179.83cm', '6\'4"', '175', '1,82',
       '180.34', '173', '178', '158', '177', '170', '188', '183', '186',
       '160', '200', '162', '189', '190cm', '190', '169', '176', '192',
       '182', '185', '155', '164', '166', '163', '165'], dtype=object)

In [131]:
df.height_cm = df.height_cm.apply(update_height)

In [132]:
pd.unique(df.height_cm)

array([152.  , 179.  , 180.  , 157.  , 179.83, 193.04, 175.  , 182.  ,
       180.34, 173.  , 178.  , 158.  , 177.  , 170.  , 188.  , 183.  ,
       186.  , 160.  , 200.  , 162.  , 189.  , 190.  , 169.  , 176.  ,
       192.  , 185.  , 155.  , 164.  , 166.  , 163.  , 165.  ])

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            51 non-null     int64
 1   timestamp     51 non-null     datetime64[ns]
 2   gender        51 non-null     object
 3   eye_color     51 non-null     object
 4   commute_mins  51 non-null     float64
 5   height_cm     51 non-null     float64
 6   date          51 non-null     object
 7   time          51 non-null     object
 8   year          51 non-null     int32
dtypes: datetime64[ns](1), float64(2), int32(1), int64(1), object(4)
memory usage: 3.5+ KB

In [134]:
df.describe()

,id,timestamp,commute_mins,height_cm,year
count,51.000000,51,51.000000,51.000000,51.000000
mean,35.980392,2019-12-27 11:44:24.039215872,35.764706,176.023725,2019.235294
min,0.000000,2018-09-24 15:31:57,0.000000,152.000000,2018.000000
25%,19.500000,2018-10-04 13:55:30,17.500000,166.000000,2018.000000
50%,36.000000,2020-09-30 11:34:10,30.000000,177.000000,2020.000000
75%,52.500000,2020-09-30 15:25:07,42.500000,183.000000,2020.000000
max,74.000000,2020-10-08 11:48:00,150.000000,200.000000,2020.000000
std,21.029018,NaN,29.746656,11.699434,0.929263

**We have been told by the data
collector that they have found
the individuals with NaN entries.
• We have a new csv file with their
entries that we can add**

Make sure dirty_data_to_add.csv
is in our folder.

**concat**

In [135]:
df1=pd.read_csv('/content/drive/MyDrive/DSRM/Lecture_2/dirty_data_to_add.csv')

In [136]:
df1.columns

Index(['Id', 'Timestamp', 'What is your gender?', 'What colour are your eyes?',
       'On average, how long does it take you to get from home to the University (in minutes)?',
       'How tall are you (in cm)?'],
      dtype='object')

In [137]:
df1.head(1)

,Id,Timestamp,What is your gender?,What colour are your eyes?,"On average, how long does it take you to get from home to the University (in minutes)?",How tall are you (in cm)?
0,69,9/26/2018 12:46:21,Male,Blue,5,175

In [138]:
df.head(1)

,id,timestamp,gender,eye_color,commute_mins,height_cm,date,time,year
0,58,2018-09-24 15:31:57,Female,Green,50.0,152.0,2018-09-24,15:31:57,2018

In [139]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column                                                                                  Non-Null Count  Dtype
---  ------                                                                                  --------------  -----
 0   Id                                                                                      5 non-null      int64
 1   Timestamp                                                                               5 non-null      object
 2   What is your gender?                                                                    5 non-null      object
 3   What colour are your eyes?                                                              5 non-null      object
 4   On average, how long does it take you to get from home to the University (in minutes)?  5 non-null      object
 5   How tall are you (in cm)?                                                               5 non-null      int64
dtypes: int64(2), object(4)
memory usage: 372.0+ bytes

In order to do this we need to
make sure we have the same
columns.

In [140]:
columns = {'Id':'id', 'Timestamp':'timestamp', 'What is your gender?': 'gender', 'What colour are your eyes?':'eye_color', 'On average, how long does it take you to get from home to the University (in minutes)?':'commute_mins', 'How tall are you (in cm)?':'height_cm' }

In [141]:
df1.rename(columns=columns, inplace=True)

In [142]:
df1.columns

Index(['id', 'timestamp', 'gender', 'eye_color', 'commute_mins', 'height_cm'], dtype='object')

In [143]:
df.columns

Index(['id', 'timestamp', 'gender', 'eye_color', 'commute_mins', 'height_cm',
       'date', 'time', 'year'],
      dtype='object')

We use concat to
combine the two
dataframes

lets combine df and df1

In [144]:
df_combined = pd.concat([df,df1], ignore_index=True)

In [145]:
df_combined.head()

,id,timestamp,gender,eye_color,commute_mins,height_cm,date,time,year
0,58,2018-09-24 15:31:57,Female,Green,50.0,152.00,2018-09-24,15:31:57,2018.0
1,34,2018-09-25 16:36:17,Male,Black,15.0,179.00,2018-09-25,16:36:17,2018.0
2,4,2018-09-26 01:25:27,Male,Brown,27.0,180.00,2018-09-26,01:25:27,2018.0
3,73,2018-10-01 18:51:00,Female,Brown,10.0,157.00,2018-10-01,18:51:00,2018.0
4,49,2018-10-03 17:22:00,Male,Brown,20.0,179.83,2018-10-03,17:22:00,2018.0

In [146]:
df_combined.value_counts()

id  timestamp            gender             eye_color   commute_mins  height_cm  date        time      year
0   2020-09-30 15:41:22  Male               Brown       20.0          183.00     2020-09-30  15:41:22  2020.0    1
3   2018-10-09 01:37:00  Male               Brown       150.0         183.00     2018-10-09  01:37:00  2018.0    1
4   2018-09-26 01:25:27  Male               Brown       27.0          180.00     2018-09-26  01:25:27  2018.0    1
5   2020-10-08 11:48:00  Male               Blue        120.0         183.00     2020-10-08  11:48:00  2020.0    1
7   2020-09-30 14:02:20  Male               Green       35.0          190.00     2020-09-30  14:02:20  2020.0    1
8   2019-10-16 09:20:48  Female             Brown       20.0          160.00     2019-10-16  09:20:48  2019.0    1
9   2020-09-28 22:39:35  Female             Brown       40.0          157.00     2020-09-28  22:39:35  2020.0    1
10  2020-09-30 14:10:13  Female             Brown       0.0           169.00     2020-09-30  14:10:13  2020.0    1
11  2020-09-30 15:35:26  Female             Hazel       30.0          164.00     2020-09-30  15:35:26  2020.0    1
12  2018-10-04 16:02:00  Male               Brown       15.0          188.00     2018-10-04  16:02:00  2018.0    1
14  2019-10-01 11:09:00  Female             Brown       50.0          173.00     2019-10-01  11:09:00  2019.0    1
15  2018-10-04 12:06:00  Female             Brown       40.0          158.00     2018-10-04  12:06:00  2018.0    1
19  2020-09-30 15:07:20  Male               Brown       50.0          176.00     2020-09-30  15:07:20  2020.0    1
20  2020-09-30 15:53:45  Female             Brown       15.0          166.00     2020-09-30  15:53:45  2020.0    1
21  2020-09-30 11:34:10  Male               Hazel       5.0           183.00     2020-09-30  11:34:10  2020.0    1
22  2020-09-30 15:17:53  Male               Black       0.0           185.00     2020-09-30  15:17:53  2020.0    1
23  2020-09-30 15:51:18  Male               Brown       30.0          200.00     2020-09-30  15:51:18  2020.0    1
25  2020-09-30 16:51:49  Male               Brown       30.0          173.00     2020-09-30  16:51:49  2020.0    1
26  2020-09-30 12:22:36  Male               Brown       30.0          183.00     2020-09-30  12:22:36  2020.0    1
28  2018-10-04 09:19:00  Male               Green       30.0          180.34     2018-10-04  09:19:00  2018.0    1
29  2020-09-30 16:39:07  Female             Green       20.0          166.00     2020-09-30  16:39:07  2020.0    1
31  2020-09-30 17:03:36  Female             Dark brown  0.0           163.00     2020-09-30  17:03:36  2020.0    1
33  2020-09-30 15:11:03  Male               Brown       35.0          192.00     2020-09-30  15:11:03  2020.0    1
34  2018-09-25 16:36:17  Male               Black       15.0          179.00     2018-09-25  16:36:17  2018.0    1
35  2020-10-02 09:18:00  Female             Brown       90.0          165.00     2020-10-02  09:18:00  2020.0    1
36  2020-09-30 13:57:48  Female             Black       120.0         162.00     2020-09-30  13:57:48  2020.0    1
38  2019-10-01 13:25:00  Male               Hazel       15.0          175.00     2019-10-01  13:25:00  2019.0    1
39  2020-09-30 17:35:05  Male               Brown       45.0          182.00     2020-09-30  17:35:05  2020.0    1
40  2020-09-29 15:11:45  Male               Brown       30.0          200.00     2020-09-29  15:11:45  2020.0    1
42  2020-09-30 15:32:21  Female             Dark brown  60.0          155.00     2020-09-30  15:32:21  2020.0    1
43  2018-10-03 23:51:00  Prefer not to say  Brown       60.0          193.04     2018-10-03  23:51:00  2018.0    1
45  2020-09-30 14:07:08  Male               Green       40.0          190.00     2020-09-30  14:07:08  2020.0    1
46  2020-09-30 15:07:19  Male               Green       35.0          190.00     2020-09-30  15:07:19  2020.0    1
47  2020-09-30 12:08:29  Male               Hazel       60.0          162.00     2020-09-30  12:08:29  2020.0    1
48  2018-10-04 06:34:00  Male               Green       35.0          182.00     2018-10-04  06:34:00  2018.0    1
49  2018-10-03 17:22:00  Male               Brown       20.0          179.83     2018-10-03  17:22:00  2018.0    1
50  2019-09-30 14:31:41  Male               Brown       30.0          186.00     2019-09-30  14:31:41  2019.0    1
52  2020-10-01 12:39:00  Female             Blue        15.0          163.00     2020-10-01  12:39:00  2020.0    1
53  2020-09-30 12:55:57  Male               Blue        30.0          189.00     2020-09-30  12:55:57  2020.0    1
54  2020-10-07 10:08:00  Male               Brown       10.0          180.00     2020-10-07  10:08:00  2020.0    1
56  2018-10-03 23:55:00  Non binary         Blueish     40.0          175.00     2018-10-03  23:55:00  2018.0    1
57  2018-10-04 10:03:00  Male               Brown       10.0          173.00     2018-10-04  10:03:00  2018.0    1
58  2018-09-24 15:31:57  Female             Green       50.0          152.00     2018-09-24  15:31:57  2018.0    1
61  2018-10-06 16:01:00  Male               Blue        32.0          175.00     2018-10-06  16:01:00  2018.0    1
63  2020-09-30 15:12:58  Male               Brown       45.0          182.00     2020-09-30  15:12:58  2020.0    1
65  2018-10-04 13:43:00  Male               Black       20.0          177.00     2018-10-04  13:43:00  2018.0    1
66  2018-10-04 14:08:00  Female             Green       30.0          170.00     2018-10-04  14:08:00  2018.0    1
67  2018-10-04 11:00:00  Male               Blue        15.0          178.00     2018-10-04  11:00:00  2018.0    1
69  2019-09-30 14:31:48  Male               Brown       20.0          175.00     2019-09-30  14:31:48  2019.0    1
73  2018-10-01 18:51:00  Female             Brown       10.0          157.00     2018-10-01  18:51:00  2018.0    1
74  2020-09-29 17:57:05  Male               Brown       50.0          175.00     2020-09-29  17:57:05  2020.0    1
Name: count, dtype: int64

In [147]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            56 non-null     int64
 1   timestamp     56 non-null     object
 2   gender        56 non-null     object
 3   eye_color     56 non-null     object
 4   commute_mins  56 non-null     object
 5   height_cm     56 non-null     float64
 6   date          51 non-null     object
 7   time          51 non-null     object
 8   year          51 non-null     float64
dtypes: float64(2), int64(1), object(6)
memory usage: 4.1+ KB

In [148]:
len(df)

51

In [149]:
len(df1)

5

In [150]:
len(df_combined)

56

In [151]:
df_combined.head(56)

,id,timestamp,gender,eye_color,commute_mins,height_cm,date,time,year
0,58,2018-09-24 15:31:57,Female,Green,50.0,152.00,2018-09-24,15:31:57,2018.0
1,34,2018-09-25 16:36:17,Male,Black,15.0,179.00,2018-09-25,16:36:17,2018.0
2,4,2018-09-26 01:25:27,Male,Brown,27.0,180.00,2018-09-26,01:25:27,2018.0
3,73,2018-10-01 18:51:00,Female,Brown,10.0,157.00,2018-10-01,18:51:00,2018.0
4,49,2018-10-03 17:22:00,Male,Brown,20.0,179.83,2018-10-03,17:22:00,2018.0
5,43,2018-10-03 23:51:00,Prefer not to say,Brown,60.0,193.04,2018-10-03,23:51:00,2018.0
6,56,2018-10-03 23:55:00,Non binary,Blueish,40.0,175.00,2018-10-03,23:55:00,2018.0
7,48,2018-10-04 06:34:00,Male,Green,35.0,182.00,2018-10-04,06:34:00,2018.0
8,28,2018-10-04 09:19:00,Male,Green,30.0,180.34,2018-10-04,09:19:00,2018.0
9,57,2018-10-04 10:03:00,Male,Brown,10.0,173.00,2018-10-04,10:03:00,2018.0
10,67,2018-10-04 11:00:00,Male,Blue,15.0,178.00,2018-10-04,11:00:00,2018.0
11,15,2018-10-04 12:06:00,Female,Brown,40.0,158.00,2018-10-04,12:06:00,2018.0
12,65,2018-10-04 13:43:00,Male,Black,20.0,177.00,2018-10-04,13:43:00,2018.0
13,66,2018-10-04 14:08:00,Female,Green,30.0,170.00,2018-10-04,14:08:00,2018.0
14,12,2018-10-04 16:02:00,Male,Brown,15.0,188.00,2018-10-04,16:02:00,2018.0
15,61,2018-10-06 16:01:00,Male,Blue,32.0,175.00,2018-10-06,16:01:00,2018.0
16,3,2018-10-09 01:37:00,Male,Brown,150.0,183.00,2018-10-09,01:37:00,2018.0
17,50,2019-09-30 14:31:41,Male,Brown,30.0,186.00,2019-09-30,14:31:41,2019.0
18,69,2019-09-30 14:31:48,Male,Brown,20.0,175.00,2019-09-30,14:31:48,2019.0
19,14,2019-10-01 11:09:00,Female,Brown,50.0,173.00,2019-10-01,11:09:00,2019.0
20,38,2019-10-01 13:25:00,Male,Hazel,15.0,175.00,2019-10-01,13:25:00,2019.0
21,8,2019-10-16 09:20:48,Female,Brown,20.0,160.00,2019-10-16,09:20:48,2019.0
22,9,2020-09-28 22:39:35,Female,Brown,40.0,157.00,2020-09-28,22:39:35,2020.0
23,40,2020-09-29 15:11:45,Male,Brown,30.0,200.00,2020-09-29,15:11:45,2020.0
24,74,2020-09-29 17:57:05,Male,Brown,50.0,175.00,2020-09-29,17:57:05,2020.0
25,21,2020-09-30 11:34:10,Male,Hazel,5.0,183.00,2020-09-30,11:34:10,2020.0
26,47,2020-09-30 12:08:29,Male,Hazel,60.0,162.00,2020-09-30,12:08:29,2020.0
27,26,2020-09-30 12:22:36,Male,Brown,30.0,183.00,2020-09-30,12:22:36,2020.0
28,53,2020-09-30 12:55:57,Male,Blue,30.0,189.00,2020-09-30,12:55:57,2020.0
29,36,2020-09-30 13:57:48,Female,Black,120.0,162.00,2020-09-30,13:57:48,2020.0
30,7,2020-09-30 14:02:20,Male,Green,35.0,190.00,2020-09-30,14:02:20,2020.0
31,45,2020-09-30 14:07:08,Male,Green,40.0,190.00,2020-09-30,14:07:08,2020.0
32,10,2020-09-30 14:10:13,Female,Brown,0.0,169.00,2020-09-30,14:10:13,2020.0
33,46,2020-09-30 15:07:19,Male,Green,35.0,190.00,2020-09-30,15:07:19,2020.0
34,19,2020-09-30 15:07:20,Male,Brown,50.0,176.00,2020-09-30,15:07:20,2020.0
35,33,2020-09-30 15:11:03,Male,Brown,35.0,192.00,2020-09-30,15:11:03,2020.0
36,63,2020-09-30 15:12:58,Male,Brown,45.0,182.00,2020-09-30,15:12:58,2020.0
37,22,2020-09-30 15:17:53,Male,Black,0.0,185.00,2020-09-30,15:17:53,2020.0
38,42,2020-09-30 15:32:21,Female,Dark brown,60.0,155.00,2020-09-30,15:32:21,2020.0
39,11,2020-09-30 15:35:26,Female,Hazel,30.0,164.00,2020-09-30,15:35:26,2020.0
40,0,2020-09-30 15:41:22,Male,Brown,20.0,183.00,2020-09-30,15:41:22,2020.0
41,23,2020-09-30 15:51:18,Male,Brown,30.0,200.00,2020-09-30,15:51:18,2020.0
42,20,2020-09-30 15:53:45,Female,Brown,15.0,166.00,2020-09-30,15:53:45,2020.0
43,29,2020-09-30 16:39:07,Female,Green,20.0,166.00,2020-09-30,16:39:07,2020.0
44,25,2020-09-30 16:51:49,Male,Brown,30.0,173.00,2020-09-30,16:51:49,2020.0
45,31,2020-09-30 17:03:36,Female,Dark brown,0.0,163.00,2020-09-30,17:03:36,2020.0
46,39,2020-09-30 17:35:05,Male,Brown,45.0,182.00,2020-09-30,17:35:05,2020.0
47,52,2020-10-01 12:39:00,Female,Blue,15.0,163.00,2020-10-01,12:39:00,2020.0
48,35,2020-10-02 09:18:00,Female,Brown,90.0,165.00,2020-10-02,09:18:00,2020.0
49,54,2020-10-07 10:08:00,Male,Brown,10.0,180.00,2020-10-07,10:08:00,2020.0
50,5,2020-10-08 11:48:00,Male,Blue,120.0,183.00,2020-10-08,11:48:00,2020.0
51,69,9/26/2018 12:46:21,Male,Blue,5,175.00,NaN,NaN,NaN
52,0,10/03/2018 23:50,Female,Black,10,180.00,NaN,NaN,NaN
53,25,10/07/2018 22:32,Male,black,3,177.00,NaN,NaN,NaN
54,19,10/01/2020 01:45,Male,Black,I live on campus,163.00,NaN,NaN,NaN
55,22,10/01/2020 01:45,Male,Black,1hour,163.00,NaN,NaN,NaN

We can confirm the
concat has worked as
the lengths add up
and we see the 5
entries from
dirty_data_to_add.csv
at the bottom

In [152]:
df_combined2 = pd.concat([df,df1], join='inner', ignore_index=True)

In [153]:
df_combined2.head()

   id            timestamp  gender eye_color commute_mins  height_cm
0  58  2018-09-24 15:31:57  Female     Green         50.0     152.00
1  34  2018-09-25 16:36:17    Male     Black         15.0     179.00
2   4  2018-09-26 01:25:27    Male     Brown         27.0     180.00
3  73  2018-10-01 18:51:00  Female     Brown         10.0     157.00
4  49  2018-10-03 17:22:00    Male     Brown         20.0     179.83

merge two tables of same individuals

We’ve been presented with a dataset
that was answered by the same
individuals, and we want to merge
them together.

In [154]:
df2 = pd.read_csv('/content/drive/MyDrive/DSRM/Lecture_2/dirty_data_to_merge.csv')

In [155]:
df2.head()

,Id,Timestamp,What is your age (years)?,What is your favourite TV series?,Who is your favourite artist/band?,Are you a robot?
0,17,01/04/2021 09:07:03,45,Sherlock,Adele,False
1,33,01/26/2020 01:10:49,40,Sherlock,Beyonce,False
2,4,04/18/2019 17:10:45,36,One Piece,Beyonce,True
3,24,03/23/2020 19:32:31,75,One Piece,John Denver,True
4,48,09/04/2020 03:42:07,19 years old,Seinfeld,Linkin Park,False

In [156]:
columns = {'Id':'id',}

In [157]:
df2.rename(columns=columns, inplace=True)

In [158]:
df2.head()

,id,Timestamp,What is your age (years)?,What is your favourite TV series?,Who is your favourite artist/band?,Are you a robot?
0,17,01/04/2021 09:07:03,45,Sherlock,Adele,False
1,33,01/26/2020 01:10:49,40,Sherlock,Beyonce,False
2,4,04/18/2019 17:10:45,36,One Piece,Beyonce,True
3,24,03/23/2020 19:32:31,75,One Piece,John Denver,True
4,48,09/04/2020 03:42:07,19 years old,Seinfeld,Linkin Park,False

In [159]:
common_ids = df.id[df.id.isin(df2.id)]

In [160]:
print(common_ids.values)

[58 34  4 49 43 48 57 15 12 61 14 38  8  9 26 33 11 23 20 29]

In [161]:
print(len(common_ids))

20

In [162]:
columns = {'Timestamp':'timestamp', 'What is your age (years)?':'age', 'What is your favourite TV series?': 'tv_series', 'Who is your favourite artist/band?': 'artist', 'Are you a robot?':'robot'}

In [163]:
df2.rename(columns=columns, inplace=True)

In [164]:
df2.head()

   id            timestamp           age  tv_series       artist  robot
0  17  01/04/2021 09:07:03            45   Sherlock        Adele  False
1  33  01/26/2020 01:10:49            40   Sherlock      Beyonce  False
2   4  04/18/2019 17:10:45            36  One Piece      Beyonce   True
3  24  03/23/2020 19:32:31           75   One Piece  John Denver   True
4  48  09/04/2020 03:42:07  19 years old   Seinfeld  Linkin Park  False

In [165]:
df_merged = pd.merge(df,df2,on='id',how='inner')

In [166]:
df_merged.head()

,id,timestamp_x,gender,eye_color,commute_mins,height_cm,date,time,year,timestamp_y,age,tv_series,artist,robot
0,58,2018-09-24 15:31:57,Female,Green,50.0,152.00,2018-09-24,15:31:57,2018,03/14/2021 12:24:12,35,Planet Earth,John Denver,True
1,34,2018-09-25 16:36:17,Male,Black,15.0,179.00,2018-09-25,16:36:17,2018,11/01/2020 05:11:05,56 years,One Piece,Ed Sheeran,False
2,4,2018-09-26 01:25:27,Male,Brown,27.0,180.00,2018-09-26,01:25:27,2018,04/18/2019 17:10:45,36,One Piece,Beyonce,True
3,49,2018-10-03 17:22:00,Male,Brown,20.0,179.83,2018-10-03,17:22:00,2018,10/03/2018 06:38:09,27,One Piece,Adele,False
4,43,2018-10-03 23:51:00,Prefer not to say,Brown,60.0,193.04,2018-10-03,23:51:00,2018,02/27/2020 23:29:07,87,Breaking Bad,Ed Sheeran,False